- hosts: all
  sudo: yes
  gather_facts: false

  vars:
    - timezone: CET

  tasks:

    - apt: 
        update_cache: yes

    - apt:
        upgrade: dist

    - apt:
        name: ntp
        state: present

#Not supported by ansible tower :((
#    - timezone: name="{{ timezone }}"

    - filesystem: fstype=ext4 dev=/dev/xvdf

    - name: Mount up /opt
      mount:
        name: /opt
        src: /dev/xvdf
        fstype: ext4
        state: present

    - name: Install {{ item }}
      apt: state=latest name={{ item }}
      with_items:
        - mc
        - openjdk-8-jdk
        - openjdk-8-jre
        - git
        - tig

    - apt_key:
        url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
        state: present

    - apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins.repo

    - apt: 
        update_cache: yes


    #- name: restart machine
    #  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    #  async: 1
    #  poll: 0 
    #  ignore_errors: true
    
    #- pause: seconds=10

    #- name: waiting for server to come back
    #  local_action: wait_for host={{ inventory_hostname }} port=22 search_regex=OpenSSH delay=30 timeout=300

    - name: Install Jenkins
      apt: state=latest name=jenkins

    - name: Crate new jenkins home
      file: path=/opt/jenkins state=directory mode=0755 owner=jenkins

    - lineinfile:
        dest: /etc/default/jenkins
        regexp: '^JENKINS_HOME='
        line: 'JENKINS_HOME=/opt/$NAME'

    - service: name=jenkins state=restarted

    #- name: Admin password for Jenkins
    #  raw: cat /opt/jenkins/secrets/initialAdminPassword
    #  register: adminpass

    #- debug: var=adminpass

